### ISSUE TITLE
sketch assignation does not work

### ISSUE THREAD

**Issue by lucasmilin** [josephtaylor/sketch-mapper#20]
I am not able to assign a different sketch to all surfaces. Each time I select a surface, drop down display the first choice.

**Comment by elo623lj** [comment]
i have the exact same problem

**Comment by josephtaylor** [comment]
Looking into this. Seems to be that something has changed around MouseEvent handlers so that when you click on the menu to set the sketch, the surface becomes de-selected so you can never set the sketch on it.  Trying to figure out how I can determine that a click is happening inside one of the menu elements and have that _not_ affect which surfaces are selected.

**Comment by weiweikee** [comment]
Is this issue resolve? Does it still work with previous version of Processing and controlP5? If so, which version does it still work with?

**Comment by josephtaylor** [comment]
Still broken, I haven't had any time to dig into it.  Last time I looked at it I was thinking about trying to move the controls into a separate ControlP5 Window, so that clicks on them won't affect the main surface.

You could try the following combo which _should_ work:
SketchMapper 3.0.2
Processing 2.X
ControlP5 2.2.5

**Comment by damianfallas** [comment]
Im woking in a fix for this right now, using the separate ControlP5 windows approach. Right now is working at 80%. Just having some issues with controlP5.

https://github.com/damianfallas/sketch-mapper

**Comment by josephtaylor** [comment]
Big thanks to @damianfallas for a fix to this long-standing bug. Just released version `4.1.3`. The website has been updated. Processing should scrape it soon and the version will be available via the library addons in the Processing IDE.
